### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by segasai**
Here's a quick implementation of the github  actions mimicking the working parts of travis.
I've never used tox, but it seems to work. 

Barring objections I'll merge it in a couple of days.

### CODE REVIEW

**Comment by keflavich** [comment]
Thanks @segasai, this is a big help!  

I disabled the travis webhook too.

**Review by keflavich — APPROVED** [review]

**Comment by segasai** [comment]
Thanks. 
I think still the travis-ci status seems to be required for merging. 
As even after the deletion of .travis.yml it says
'continuous-integration/travis-ci Expected — Waiting for status to be reported' and 'Required statuses must pass before merging'. There must be a setting somewhere ...

**Comment by keflavich** [comment]
Following https://docs.github.com/en/github/administering-a-repository/managing-a-branch-protection-rule, it is in the settings:branches area.  Got there via https://github.com/travis-ci/travis-ci/issues/8988

**Comment by segasai** [comment]
Great! merged.

**Pull request merged**
